### ISSUE TITLE
Better way to handle yaml tests to use minimal parameters

### ISSUE THREAD

**Issue by mave007** [mave007/dns_completitude_and_compliance#3]
Current version, uses almost full yaml outputs for testing purposes, while hardcoding to ignore things like `query_time` or `['response_message_data']['id']`.

Ideally if we want to create a test for checking if the server is authoritative (`dig +norec @<server> <domain>`), the yaml file should only include a minimal portion of the response to test, like:

```yaml
-
  message:
    type: AUTH_RESPONSE
    response_message_data:
      status: NOERROR
      flags: qr aa
```
